### PR TITLE
Add rl_id and make it primary key

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by JohnFLewis** [comment]
This is completely against the intended functionality of the whole extension. I intentionally didn’t add an ID key because it wouldn’t work by the design. I completely disapprove of this change without even an attempt to discuss what is a critical breaking change to the backend functionality.

**Comment by paladox** [comment]
@Southparkfan outhparkfan asked me to do this.

**Comment by JohnFLewis** [comment]
I’m saying revert it, rl_externallink is the unique entry within the table, rl_id is a useless infinitely increasing count serving no realistic purpose

**Comment by Southparkfan** [comment]
The MediaWiki policy requires the usage of a PRIMARY KEY, so does MariaDB's replication.

I understand rl_id is not a field that has a use case at this moment (as in referencing to rl_id). However, making a BLOB field in MariaDB is not possible and throws an error. On a VARCHAR(2048), it's technically possible, but 2048 is not long enough to accomodate all URLs (certain wikis have URLs longer than ther). Finally, surrogate keys won't have to be changed in the future, unlike natural keys. I don't know if you plan to reference to the rottenlinks table from other tables in the future, but if so, I would expect a surrogate to be very useful.

_If_ a longer VARCHAR is stil preferred as primary key, please let me know. In that case we can convert rl_externallink to become a VARCHAR(8192) or similar.

**Comment by JohnFLewis** [comment]
The VARCHAR is the preferred method, which is what my original plan was which was committed.

**Comment by Southparkfan** [comment]
Ack. I will convert rl_externallink to varchar(8192), make that one a PK and remove rl_id.

**Pull request merged**
